//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemCallService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SystemCallServiceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SystemCallServiceSettings defaultInstance = ((SystemCallServiceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SystemCallServiceSettings())));
        
        public static SystemCallServiceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SystemCallServiceData")]
        public string DataDirectory {
            get {
                return ((string)(this["DataDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("debug_log.txt")]
        public string DebugLogFilename {
            get {
                return ((string)(this["DebugLogFilename"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pid int, Start DATETIME, StartRelativeMSec DOUBLE, StopRelativeMSec DOUBLE, Comma" +
            "ndLine TEXT, ImageFileName TEXT, ParentID int, Guid TEXT PRIMARY KEY, ProcessKey" +
            " INTEGER, Md5 TEXT")]
        public string ProcessTableStructure {
            get {
                return ((string)(this["ProcessTableStructure"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pid int, PidStartRelativeMSec DOUBLE, Tid int, Start DateTime, StartRelativeMSec " +
            "DOUBLE, StopRelativeMSec DOUBLE, Guid TEXT PRIMARY KEY, ProcessGuid TEXT ")]
        public string ThreadTableStructure {
            get {
                return ((string)(this["ThreadTableStructure"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NtoskrnlVersion TEXT, NtoskrnlMD5 TEXT, Cores int, Hostname TEXT, HostSampling DO" +
            "UBLE, ProcessSampling DOUBLE, ThreadSampling DOUBLE, HostTrace INT, ProcessTrace" +
            " INT, ThreadTrace INT")]
        public string SystemInfoTableStructure {
            get {
                return ((string)(this["SystemInfoTableStructure"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Verbosity {
            get {
                return ((int)(this["Verbosity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600000")]
        public double AutoResetMs {
            get {
                return ((double)(this["AutoResetMs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("symbols")]
        public string SymbolSubfolder {
            get {
                return ((string)(this["SymbolSubfolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ntsensors.txt")]
        public string NtSensorList {
            get {
                return ((string)(this["NtSensorList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120000")]
        public float CommitInterval {
            get {
                return ((float)(this["CommitInterval"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public double ThreadDeletionDelay {
            get {
                return ((double)(this["ThreadDeletionDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public double ProcessDeletionDelay {
            get {
                return ((double)(this["ProcessDeletionDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double MinBackoff {
            get {
                return ((double)(this["MinBackoff"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TracePerProcess {
            get {
                return ((bool)(this["TracePerProcess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public long MaxTraceSyscalls {
            get {
                return ((long)(this["MaxTraceSyscalls"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string HostIdentifier {
            get {
                return ((string)(this["HostIdentifier"]));
            }
            set {
                this["HostIdentifier"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AnonymizeHostname {
            get {
                return ((bool)(this["AnonymizeHostname"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScrubCommandLine {
            get {
                return ((bool)(this["ScrubCommandLine"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TraceHostLevel {
            get {
                return ((bool)(this["TraceHostLevel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TracePerThread {
            get {
                return ((bool)(this["TracePerThread"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProfileCode {
            get {
                return ((bool)(this["ProfileCode"]));
            }
        }
    }
}
